[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
    -std=gnu++17
lib_deps =
    https://github.com/ESPressio-Development-Platform/ESPressio-System.git#feature/1-system-memory-policy
lib_extra_dirs =
    ../..
